use_frameworks!

platform :ios, '9.0'

target 'Verifiedly_Example' do
  pod 'Verifiedly', :path => '../'
  pod 'Alamofire', '~> 5.4'
  pod 'SwiftyJSON', '~> 4.0'

  target 'Verifiedly_Tests' do
    inherit! :search_paths

    
  end
end
