use_frameworks!

platform :ios, '10.0'

target 'Verifiedly_Example' do
  pod 'Verifiedly', :path => '../'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'RappleProgressHUD'
  pod 'SwiftMessages'
  pod 'lottie-ios'

  target 'Verifiedly_Tests' do
    inherit! :search_paths

    
  end
end
